# Generated by Django 4.1.2 on 2022-11-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_reviews_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
