# Generated by Django 4.1.2 on 2022-10-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_category_img_offers_img_products_img1_products_img2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="ads")),
                ("date", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="products",
            name="info",
            field=models.TextField(default=""),
        ),
    ]
