# Generated by Django 4.1.2 on 2022-10-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_category_subcat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcat",
            field=models.ManyToManyField(blank=True, to="shop.subcategory"),
        ),
    ]
