# Generated by Django 4.1.2 on 2022-11-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_alter_offers_name_alter_products_desc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="length",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="products",
            name="pattern",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="products",
            name="sec_color",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
