# Generated by Django 4.1.2 on 2022-11-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_alter_products_length_alter_products_pattern_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="shipping",
            field=models.IntegerField(default=0),
        ),
    ]
