# Generated by Django 4.1.2 on 2022-11-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_products_shipping"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="stock",
        ),
        migrations.AddField(
            model_name="products",
            name="stock_l",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="stock_m",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="stock_s",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="stock_xl",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="products",
            name="stock_xs",
            field=models.IntegerField(default=0),
        ),
    ]
