# Generated by Django 4.1.2 on 2022-12-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_products_avg_review_products_tot_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
