# Generated by Django 4.1.2 on 2022-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
