# Generated by Django 4.1.2 on 2022-11-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0004_alter_items_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
