# Generated by Django 4.1.2 on 2022-11-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_alter_items_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="size",
            field=models.CharField(default="", max_length=5),
        ),
    ]
