# Generated by Django 4.1.2 on 2022-11-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_products_shipping"),
        ("cart", "0007_orders"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="tot_amount",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="items",
        ),
        migrations.AddField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.products",
            ),
        ),
        migrations.AddField(
            model_name="orders",
            name="size",
            field=models.CharField(default="", max_length=2),
        ),
    ]
