# Generated by Django 4.1.2 on 2022-11-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_rename_tot_amount_orders_amount_remove_orders_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
