# Generated by Django 4.1.2 on 2022-11-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_products_shipping"),
        ("cart", "0009_orders_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="cart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="cart.cartlist"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="product",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="shop.products",
            ),
        ),
    ]
