# Generated by Django 4.1.2 on 2022-11-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0010_alter_orders_cart_alter_orders_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="cart",
            field=models.CharField(max_length=50),
        ),
    ]
